apiVersion: v1
kind: Service
metadata:
  name: auditor-web-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: auditor-web-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditor-web-svc
  labels:
    app: auditor-web-svc
spec:
  selector:
    matchLabels:
      app: auditor-web-svc

  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%

  template:
    metadata:
      labels:
        app: auditor-web-svc
    spec:
      containers:
        - name: auditor-web-svc
          image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${IMAGE_LABEL}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: aws_access_key

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: aws_secret_key

            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: aws_region

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: databae_url

            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: next_auth_url

            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: github_client_id

            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: github_client_name

            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: bucket_name

            - name: BULK_SAVE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: bulk_save_api_key

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: google_client_id

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: google_client_secret

      imagePullSecrets:
        - name: regcred
